[tool.poetry]
name = "libretro-finder"
version = "0.1.0"
description = "Command line utility that looks for specific BIOS files for libretro cores and, if found, refactors them to the expected format as documented [here](https://github.com/libretro/libretro-database/blob/4a98ea9726b3954a4e5a940d255bd14c307ddfba/dat/System.dat)."
authors = ["Jasper Siebring <j.siebring92@gmail.com>"]
license = "GNU General Public License v3.0"
readme = "README.md"
packages = [{include = "libretro_finder"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.25.1"
pandas = "^2.0.3"
tqdm = "^4.65.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3"
pylint = "^2.17.4"
twine = "^4.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
