name: Quality control and automated release
on:
  pull_request: # Pull request events (default: open, synchronized, reopened) in any branch triggers the workflow.
  push:
    branches:
      - main # Pushes to main (i.e. after a merged PR)
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installing Poetry globally
        run: pipx install poetry
      - name: Installing Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: poetry
      
      
      - name: Installing Poetry environment
        run: poetry install

      - name: echo poetry
        run : cat poetry.lock
      - name: Setting tag to package version
        shell: bash
        run: |
          echo "RELEASE_NAME=$(poetry version | tr ' ' '-')" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(poetry version -s)" >> $GITHUB_ENV
      