name: Poetry testing
on: [push]
jobs:
  Poetry-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installing Poetry
        run: pipx install poetry
      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            dpkg-dev \
            build-essential \
            freeglut3-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libgstreamer-plugins-base1.0-dev \
            libgtk-3-dev \
            libjpeg-dev \
            libnotify-dev \
            libpng-dev \
            libsdl2-dev \
            libsm-dev \
            libunwind-dev \
            libtiff-dev \
            libwebkit2gtk-4.0-dev \
            libxtst-dev \
            libgtk2.0-dev      
      - name: Installing Poetry environment
        run: poetry install
      - name: Running pytest
        run: poetry run pytest -v
      - name: Running mypy
        run: poetry run mypy libretro_finder/ config/ tests/
      - name: Running pylint
        run: poetry run pylint libretro_finder/ config/ tests/
